### PR TITLE
Transition to V3

### PR DESCRIPTION
**Pull request by jasonuher**
This is an initial attempt at transitioning to the V3 API.  I have been using it without issue for a few days now and it seems to work for most cases.

A few notes:
I moved around some of the request code to keep API related stuff in a single module
I added support for python logging
Some of the task creation functions are left stubbed out (I don't use those)

### CODE REVIEW

**Review by rbavishi — APPROVED** [review]

**Review by rbavishi — APPROVED** [review]

**Comment by jasonuher** [comment]
I'm going to close this pull request at this point, I think the V3 transition is structurally complete. There should probably be some refactoring where I "shoehorned" the new API into the old code, but that can be separate fixes.

**Comment by jasonuher** [comment]
I realized the detial view doesn't show up anymore (I don't really use it, so I hadn't noticed).  Gonna fix that before we close this up

**Comment by jasonuher** [comment]
I think this is done now if you want to test/merge it.  Again, some refactoring is probably necessary, but all "Fix for V3 API" stuff is done.   A "squash and merge" might be appropriate here.

**Comment by jasonuher** [comment]
@rbavishi unless there's something you'd like me to change, can you squash merge this?  I have some more features I'd like to put PRs in for but they're all dependent on this one

**Comment by rbavishi** [comment]
@jasonuher Sorry, I've been really busy for the past month. Thanks a lot for your contributions!

**Comment by jasonuher** [comment]
I don't think it merged the changes

**Comment by rbavishi** [comment]
@jasonuher I'm confused. Your other pull request's name was also related to the API V3 change. I assumed it contained the changes proposed here and merged it. Or am I making a complete mess of it?

**Pull request merged**
